CREATE TABLE EMPLOYEES
(
    EMPLOYEE_ID       CHAR(36) PRIMARY KEY,
    FIRST_NAME    VARCHAR(255) UNIQUE NOT NULL,
    LAST_NAME VARCHAR(255)        NOT NULL,
    DEPARTMENT   VARCHAR(255)        NOT NULL,
    SALARY   INT(255)        NOT NULL
);